export const serviceHelper = [
    {
        type:"post",
        controllerName:"Login",
       
    },
    {
        type:"post",
        controllerName:"VerifyOTP",
    },
  
    {
        type:"post",
        controllerName:"ImageUpload"
    },
    {
        type:"post",
        controllerName:"FetchImage"
    },
    {
        type:"post",
        controllerName:"UpdateUserProfile"
    },
    {
        type:"post",
        controllerName:"FetchSavedAddresses"
    },
    {
        type:"post",
        controllerName:"SaveUserAddress"
    },
    {
        type:"post",
        controllerName:"EditUserAddress"
    },
    {
        type:"post",
        controllerName:"DeleteUserAddress"
    },
    {
        type:"get",
        controllerName:"FetchSingleUserById"
    },
    {
        type:"post",
        controllerName:"SaveUserPreferences"
    },
    {
        type:"get",
        controllerName:"GetUserPreferencesByUserId"
    },
    {
        type:"post",
        controllerName:"SaveOrUpdateUserPreferences"
    },
    {
        type:"post",
        controllerName:"FetchSearchResultsByKeyWord"
    },
    {
        type:"post",
        controllerName:"FetchRestaurantDetailsById"
    },
    {
        type:"post",
        controllerName:"UpdateRestoLike"
    },
    {
        type:"post",
        controllerName:"CreateNewBuddyList"
    },
    {
        type:"post",
        controllerName:"ModifyBuddyList"
    },
    {
        type:"get",
        controllerName:"FetchBuddiesListsByUserId"
    },
    {
        type:"post",
        controllerName:"UpdateUserOnlineStatus"
    },
    {
        type:"post",
        controllerName:"FetchUserDetailsByPhoneNumber"
    },
    {
        type:"post",
        controllerName:"FetchBuddyListDetailsByBuddyListId"
    },
    {
        type:"post",
        controllerName:"FetchAllRestaurants"
    },
    {
        type:"post",
        controllerName:"SendInviteSMSToNonRegdUser"
    },
    {
        type:"post",
        controllerName:"CreateNewEvent"
    },
    {
        type:"post",
        controllerName:"GetAllEventsByPhoneNumber"
    },
    {
        type:"post",
        controllerName:"GetAllEventAlbumsSharedToUserByPhoneNumber"
    },
    {
        type:"post",
        controllerName:"MemoryImageUpload"
    },
    {
        type:"post",
        controllerName:"GetEventDetailsByEventId"
    },
    {
        type:"post",
        controllerName:"GetAllEventsByPhoneNumber"
    },
    {
        type:"post",
        controllerName:"UpdateEventAlbumsSharedToUserByPhoneNumber"
    },
    {
        type:"get",
        controllerName:"EventUserdetails"
    },
    {
        type:"get",
        controllerName:"UpdateEventStatus"
    },
    {
        type:"get",
        controllerName:"GetPendingAcceptDeclineStatusOfInvitees"
    },
    {
        type:"post",
        controllerName:"SharePhotosToBuddies"
    },
    {
        type:"post",
        controllerName:"SaveFCMTokenToDatabase"
    },
    {
        type:"post",
        controllerName:"SendPushNotificationFCM"
    },
    {
        type:"get",
        controllerName:"GetRestuarntsReviews"
    },
    {
        type:"post",
        controllerName:"CreateRestReview"
    },
    {
        type:"get",
        controllerName:"GetAllEventsCreatedByUser"
    },
    {
        type:"get",
        controllerName:"GetUserFaviourties"
    },
    {
        type:"get",
        controllerName:"UpdateFaviourtiesBuddies"
    },
    {
        type:"get",
        controllerName:"GetEventAlbumSharedByUser"
    },
    {
        type:"get",
        controllerName:"GetUserSharedAlbums"
    },
    {
        type:"get",
        controllerName:"GetUserSharedDetails"
    },

    {
        type:"post",
        controllerName:"GetNotificationsByUserId"
    },
    {
        type:"post",
        controllerName:"CreateNotification"
    },
    {
        type:"post",
        controllerName:"UpdateNotification"
    },
    {
        type:"post",
        controllerName:"SendPushNotificationForAcceptEvent"
    },

]